name = "telegold" 
main = "src/index.ts" 
compatibility_date = "2024-01-01" 
workers_dev = true

# =========================================================
# KV BINDING: This connects the KV Namespace to your Worker
# =========================================================
[[kv_namespaces]]
# The 'binding' is the name your Worker code uses (env.KV_BINDING)
binding = "KV_BINDING" 
# The 'id' is the unique ID for your KV Namespace
id = "59ff4573092e4901b72f53d96d999aef" 

# Note: The BOT_TOKEN must be set as a Secret in the Cloudflare dashboard.
